version: 2

jobs:
  build:
    docker: circleci/node:latest
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: yarn install

      - run:
          name: Build for production
          command: yarn build:production
  test:
    docker: circleci/node:latest
    steps:
      - run:
          name: Test
          command: yarn test
  deploy:
    docker: circleci/node:latest
    steps:
      - run:
          name: Deploy to gh-pages
          command: yarn deploy

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
