version: 2

jobs:
  startup:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: yarn install

  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - run:
          name: Build for production
          command: yarn build:production
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - run:
          name: Test
          command: yarn test
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Deploy to gh-pages
          command: yarn deploy

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - startup
      - build:
          requires:
            - startup
      - test:
          requires:
            - startup
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
